name: Build & Test WPF App

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: RegisterDocuments.sln
      LANG: ru_RU.UTF-8
      LC_ALL: ru_RU.UTF-8

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore
      run: dotnet restore $env:Solution_Name

    - name: Build
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration /m
      env:
        Configuration: ${{ matrix.configuration }}
        
    - name: Test
      run: dotnet test $env:Solution_Name --configuration $env:Configuration --no-build --logger trx
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Publish
      run: msbuild RegisterDocuments/RegisterDocuments.csproj /t:Publish /p:Configuration=${{ matrix.configuration }} /p:PublishDir=bin/${{ matrix.configuration }}/publish/ /p:PublishProtocol=FileSystem /p:RuntimeIdentifier=win-x64 /p:PublishSingleFile=false /p:SelfContained=false /m
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: RegisterDocuments-${{ matrix.configuration }}
        path: RegisterDocuments/bin/${{ matrix.configuration }}/publish/
        if-no-files-found: error